points:
  zones:
    origin:
      key:
        width: 1
        height: 1
    holes:
        anchor:
          ref: origin
          shift: [-23/2, -58/2]
        columns:
          left:
          right:
        rows:
          bottom:
          top:
        key:
          width: 6
          height: 6
          padding: 58
          spread: 23
    MCU:
      anchor:
        ref: origin
        shift: [3, 0]
      key:
        width: 21
        height: 51
    pins:
      anchor:
        ref: origin
        shift: [-23/2, 0]
      key:
        width: 5
        height: 51
    I2C_extender:
      anchor:
        ref: MCU
      key:
        width: 22.76
        height: 10
        rotate: 90

outlines:
  pcb_perimeter:
    - what: rectangle
      where: origin
      size: [30, 65]
      corner: 3

pcbs:
  rpi_pico_to_zero_adapter:
    outlines:
      main:
        outline: pcb_perimeter
    footprints:
      rpi_pico:
        what: rpi_pico
        where: 
          ref: MCU
        params:
          orientation: up
          side: B
      I2C_extender:
        what: MCP23008
        where:
          ref: I2C_extender
        params:
          SCL: GP21
          SDA: GP20
          A2: GND
          A1: GND
          A0: GND
          RESET: VBUS
          NC: ''
          INT: ''
          VSS: GND
          VDD: VBUS
      pins:
        what: PinHeader_2x20
        where:
          ref: pins
          shift: [-2.54/2, (51/2) - (2.54/2) - 0.1]
        params:
          side: B
          flip: true
          V5: VBUS
          GP_EXTRA: EXTRA_0
          GND: GND
          GP14: GP0
          GP15: GP1
          GP18: GP13
          GP23: GP4
          GP24: GP5
          GP25: GP6
          GP8: GP18
          GP7: GP7
          GP1: GP8
          GP12: GP9
          GP16: EXTRA_4
          GP20: GP12
          GP21: GP10
          GP26: GP14
          GP19: GP11
          GP13: GP15
          GP6: EXTRA_1
          GP5: EXTRA_2
          GP0: EXTRA_3
          GP11: GP17
          GP9: GP19
          GP10: GP16
          V3_AUX: ADC_VREF
          GP22: GP26
          GP27: GP27
          GP17: GP28
          AGND: AGND
          GP4: GP22
          GP3: GP3
          GP2: GP2
          V3: V3
         
      mounting_holes:
        what: MountingHole
        where:
          - /^holes_.*/